### ISSUE TITLE
Not able to create new project

### ISSUE THREAD

**Issue by Rikujolla** [eekkelund/harbour-tIDE#11]
SailfishOS 2.0.5.6 (Haapajoki) (armv7hl)
'---
[nemo@Sailfish ~]$ harbour-tide
[D] QWaylandEglClientBufferIntegration::QWaylandEglClientBu
fferIntegration:62 - Using Wayland-EGL
[W] MLocalThemeDaemonClient::MLocalThemeDaemonClient:103 -
Could not find any zN.M subdirs!
[W] MLocalThemeDaemonClient::MLocalThemeDaemonClient:129 -
Theme dir "/usr/share/themes/jolla-ambient/meegotouch/z1.0/
" does not exist
[D] QPythonPriv::formatExc:612 - "PyOtherSide error: Traceb
ack (most recent call last):

File "/usr/share/harbour-tide/qml/python/createProject.py
", line 12, in create
os.mkdir(projectPath)

PermissionError: [Errno 13] Lupa evätty: '/home/nemo/tIDE/P
rojects'
"
[D] onError:87 - python error: Return value of PyObject cal
l is NULL: Traceback (most recent call last):

File "/usr/share/harbour-tide/qml/python/createProject.py
", line 12, in create
os.mkdir(projectPath)

**Comment by Rikujolla** [comment]
I tried to create a new project and error message as above appeared. The project could not be done.

**Comment by eekkelund** [comment]
Thanks. Did you have any projects there before? Did you create project in rootmode?(root@tIDE)
Quick fix would be now to execute `` chown -R nemo:nemo /home/nemo/tIDE/ `` as root. Thanks for reporting I have to fix this :)

**Comment by eekkelund** [comment]
And hopefully more permanent fix, could you try this and please report back?:)
[harbour-tide-0.2.5-2.armv7hl.zip](https://github.com/eekkelund/harbour-tIDE/files/746117/harbour-tide-0.2.5-2.armv7hl.zip)

**Comment by Rikujolla** [comment]
Hi, it was my fist project. I tried to make the project in normal mode. Your fix removed the problem, thanks for that. Seems to be a promising tool for the development and for installation from sources.
