### ISSUE TITLE
[W] displayFileDialog:308 - No filename specified...

### ISSUE THREAD

**Issue by Rikujolla** [eekkelund/harbour-tIDE#12]
Hi, 
I cloned  with git my project to Projects folder:
[nemo@Sailfish Projects]$  git clone https://github.com/Rik
ujolla/oontoissa
I opened the project and tried to run the app. The error message in application output window was:
[W] displayFileDialog:308 - No filename specified...

I could reproduce the behaviour also with another app:
[nemo@Sailfish Projects]$  git clone https://github.com/gol
dfrapper/BabyLogger
The version of the tIDE is 0.2.5-2

**Comment by eekkelund** [comment]
Thanks again:) Yes I can see the problem, will fix today. :)

**Comment by eekkelund** [comment]
Hi could you please try this and report back? :)
I would like to remind that tIDE does not yet support compiling/building c++ apps..

[harbour-tide-0.2.5-3.armv7hl.rpm.gz](https://github.com/eekkelund/harbour-tIDE/files/747675/harbour-tide-0.2.5-3.armv7hl.rpm.gz)

**Comment by Rikujolla** [comment]
Good work. Now it works.Thanks!
