### ISSUE TITLE
Projects folder not created automatically

### ISSUE THREAD

**Issue by Rikujolla** [eekkelund/harbour-tIDE#14]
The about&help page tells the projects are located in /home/nemo/tIDE/Projects folder. It would be nice the software to create this folder automatically during installation process. Now you have to make it by creating the new project with tIDE or manually from terminal. I know this is minor issue but adding the folder it would help ordinary user to start using tIDE.

**Comment by eekkelund** [comment]
Thanks for suggestion:)
Yeah, I think it makes sense, I could add this to next release.
 If you have more feedback/ suggestions, they are more than welcome :)

**Comment by Rikujolla** [comment]
One suggestion could be to somehow to automize the installation and keeping apps up to date from source in github. For me it is ok to clone the repository to projects folder with terminal. For users with limited coding skills or motivation it would be enough to feed the repository address and press install. The tIDE could do the rest.

**Comment by eekkelund** [comment]
I added the previous suggestion:) 
What do you mean by automating installation? What installation?
Git gui support is planned for the 0.3 release, one should be able to clone/pull/push etc. repos :)

**Comment by Rikujolla** [comment]
Works fine!
