### ISSUE TITLE
Stable code for tab button

### ISSUE THREAD

**Issue by GoAlexander** [eekkelund/harbour-tIDE#4]
`var previousCursorPosition = myTextArea.cursorPosition;`
`myTextArea.text = myTextArea.text.slice(0, myTextArea.cursorPosition) + "\t" + myTextArea.text.slice(myTextArea.cursorPosition, myTextArea.text.length);`
`myTextArea.cursorPosition = previousCursorPosition + 1;`

Where myTextArea - your TextArea :)
If you want to make buttons as in `Editor.` you can take the code from: https://github.com/GoAlexander/harbour-editor/blob/master/qml/components/MenuButton.qml

**Comment by eekkelund** [comment]
This is implemented in keyboard now:)

4f1c2ce0b551f5015e4df6008dcfddabad6efe79

**Comment by GoAlexander** [comment]
Good :)
