### ISSUE TITLE
Respect system allowed orientations settings.

### ISSUE THREAD

**Issue by elros34** [eekkelund/harbour-tIDE#9]
There are global allowed orientations settings and they should be respected by apps.
    allowedOrientations: defaultAllowedOrientations
_defaultPageOrientations: defaultAllowedOrientations
https://sailfishos.org/develop/docs/silica/qml-sailfishsilica-sailfish-silica-applicationwindow.html/

**Comment by eekkelund** [comment]
Thanks, so 
```
allowedOrientations: Orientation.All
_defaultPageOrientations: Orientation.All
```
in the main qml file is not good way to do it? It should be done like you posted^ ?:) 
Hmm, I don't understand the difference and what is affected.

**Comment by elros34** [comment]
I mean 
allowedOrientations: Orientation.All
_defaultPageOrientations: Orientation.All
should be replaced with
allowedOrientations: defaultAllowedOrientations
_defaultPageOrientations: defaultAllowedOrientations
in harbour-tide.qml

defaultAllowedOrientations is defined in dconf /desktop/sailfish/silica/default_allowed_orientations
For example: when I type using hw keyboard I don't want to tIDE rotate to inverted landscape but others may like it. So I think the best would be to use system settings and not hardcode it in tIDE.

**Comment by eekkelund** [comment]
Oh okay, thank you :)
I will change it!

**Comment by eekkelund** [comment]
Fixed and is in new release:)
https://github.com/eekkelund/harbour-tIDE/commit/c0028bcb659f35eecaafd2a6480488be329e62af
Thank you :)
